set(ZXING_C_API OFF)
set(ZXING_EXAMPLES OFF)
set(ZXING_ENABLE_UNICODE OFF)


set(ZXING_ENABLE_1D OFF)
set(ZXING_ENABLE_AZTEC OFF)
set(ZXING_ENABLE_DATAMATRIX OFF)
set(ZXING_ENABLE_MAXICODE OFF)
set(ZXING_ENABLE_PDF417 OFF)
