/*
 * UniThen
 * Copyright (C) 2026 Moritz Zwerger
 *
 * This program is free software: you can redistribute it and/or modify it under the terms of the GNU General Public License as published by the Free Software Foundation, either version 3 of the License, or (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.
 * You should have received a copy of the GNU General Public License along with this program. If not, see <https://www.gnu.org/licenses/>.
 *
 * This software is not affiliated with UniNow GmbH, the provider/developer of the booking system.
 */

package de.bixilon.unithen.storage.sql

import kotlinx.coroutines.runBlocking
import kotlinx.coroutines.sync.Mutex
import java.io.File
import java.sql.*
import kotlin.time.Instant
import kotlin.uuid.Uuid

private fun PreparedStatement.bind(vararg parameters: Any?) {
    for ((index, parameter) in parameters.withIndex()) {
        val actual = index + 1
        when (parameter) {
            null -> setNull(actual, Types.NULL)
            is Int -> setInt(actual, parameter)
            is Long -> setLong(actual, parameter)
            is String -> setString(actual, parameter)
            is Instant -> setLong(actual, parameter.epochSeconds)
            is Uuid -> setString(actual, parameter.toString())
            is ByteArray -> setBytes(actual, parameter)
            is Enum<*> -> setString(actual, parameter.name)
            is Boolean -> setBoolean(actual, parameter)
            else -> throw IllegalArgumentException("Unknown parameter type: $parameter")
        }
    }
}


private fun Connection.createStatement(sql: String, vararg parameters: Any?, autoGeneratedKeys: Int? = null): PreparedStatement {
    val statement = autoGeneratedKeys?.let { prepareStatement(sql, it) } ?: prepareStatement(sql)
    statement.bind(*parameters)

    return statement
}

class JvmSqlHelper(file: File?) : SQLiteHelper {
    private val lock = Mutex(false)
    private val connection by lazy { DriverManager.getConnection(if (file == null) "jdbc:sqlite::memory:" else "jdbc:sqlite:$file") }

    init {
        Class.forName("org.sqlite.JDBC", true, JvmSqlHelper::class.java.classLoader)
        file?.parentFile?.mkdirs()
    }

    fun onCreate(connection: SQLiteHelper.UpdateConnection) {
        connection.executeBatch("schema")
    }

    private fun onUpgrade(connection: SQLiteHelper.UpdateConnection, version: Int) {
        for (version in (version + 1)..SqlStorage.VERSION) {
            try {
                connection.executeBatch("migrations/${version}")
            } catch (error: Throwable) {
                throw SQLException("Error during database migration $version: ${error.message}", error)
            }
        }
    }

    override suspend fun load() {
        val version = query().use { it.query("PRAGMA user_version;").use { it.moveToNext(); it.getInt(0) } }
        if (version == SqlStorage.VERSION) return
        if (version > SqlStorage.VERSION) {
            throw IllegalStateException("Database was created with a newer version: $version >= ${SqlStorage.VERSION}")
        }

        val connection = update()

        connection.use {
            it.transaction {
                if (version == 0) {
                    onCreate(connection)
                } else {
                    onUpgrade(connection, version)
                }
                it.execute("PRAGMA user_version = ${SqlStorage.VERSION};")
            }
        }
    }

    override fun query(): SQLiteHelper.QueryConnection {
        runBlocking { lock.lock() }
        return JvmQueryConnection(connection)
    }

    override fun update(): SQLiteHelper.UpdateConnection {
        runBlocking { lock.lock() }
        return JvmUpdateConnection(connection)
    }

    override fun close() {
        connection.close()
    }

    private open inner class JvmQueryConnection(val connection: Connection) : SQLiteHelper.QueryConnection {

        override fun query(sql: String, vararg parameters: Any?): SQLiteHelper.Cursor {
            val statement = connection.createStatement(sql, *parameters)

            return SqlCursor(statement.executeQuery())
        }

        override fun close() {
            lock.unlock()
        }
    }

    private inner class JvmUpdateConnection(connection: Connection) : JvmQueryConnection(connection), SQLiteHelper.UpdateConnection {
        private var transaction = false

        override fun execute(sql: String, vararg parameters: Any?): Int {
            val statement = connection.createStatement(sql, *parameters)
            return statement.use { it.executeUpdate() }
        }

        override fun insert(sql: String, vararg parameters: Any?): Int {
            val statement = connection.createStatement(sql, *parameters, autoGeneratedKeys = Statement.RETURN_GENERATED_KEYS)

            return statement.use { it.executeUpdate(); statement.generatedKeys.let { it.next(); it.getInt(1) } }
        }

        override fun <T> transaction(block: () -> T): T {
            if (transaction) throw IllegalStateException("Nested transactions are unsupported!")
            try {
                this.transaction = true
                connection.autoCommit = false
                return block.invoke()
            } finally {
                this.transaction = false
                connection.commit()
                connection.autoCommit = true
            }
        }
    }

    class SqlCursor(val cursor: ResultSet) : SQLiteHelper.Cursor {
        override fun getBlob(index: Int) = cursor.getBytes(index + 1)
        override fun getBlobOrNull(index: Int) = cursor.getBytes(index + 1)

        override fun getString(index: Int) = cursor.getString(index + 1)
        override fun getStringOrNull(index: Int) = cursor.getString(index + 1)

        override fun getInt(index: Int) = cursor.getInt(index + 1)
        override fun getLong(index: Int) = cursor.getLong(index + 1)

        override fun isNull(index: Int): Boolean {
            cursor.getObject(index + 1)
            return cursor.wasNull()
        }

        override fun moveToNext() = cursor.next()

        override fun close() = cursor.close()

        override fun isEmpty() = !cursor.next()
    }
}
